<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping" nsURI="http://www.servicifi.org/gelato/language/kernel/mapping"
    nsPrefix="mapping">
  <eClassifiers xsi:type="ecore:EClass" name="KernelElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CobolElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapsTo" upperBound="-1"
        eType="#//KernelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CobolStatement" abstract="true" eSuperTypes="#//CobolElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CobolProcedure" abstract="true" eSuperTypes="#//CobolElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CobolReferenceableElement" abstract="true"
      eSuperTypes="#//CobolElement"/>
  <eSubpackages name="commons" nsURI="http://www.servicifi.org/gelato/language/kernel/mapping/commons"
      nsPrefix="commons">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LabellableElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URIableElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="core" nsURI="http://www.servicifi.org/gelato/language/kernel/mapping/core"
      nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="KernelCompilationUnit" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceableElements"
          upperBound="-1" eType="#//core/KernelReferenceableElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" eType="#//core/KernelProcedure"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MappingRoot" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="CobolCompilationUnitxsxsx" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" eType="#//core/CobolProcedurexaxa"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CobolProcedurexaxa" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsTo" eType="#//core/KernelProcedure"
          eOpposite="#//core/KernelProcedure/mapsFrom"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceableElements"
          upperBound="-1" eType="#//core/CobolReferenceableElementaxax"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//core/CobolStatementaxaxax" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KernelProcedure" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsFrom" eType="#//core/CobolProcedurexaxa"
          eOpposite="#//core/CobolProcedurexaxa/mapsTo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kernelStatements" upperBound="-1"
          eType="#//core/KernelStatement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CobolStatementaxaxax" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsTo" upperBound="-1"
          eType="#//core/KernelStatement" eOpposite="#//core/KernelStatement/mapsFrom"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KernelStatement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsFrom" upperBound="-1"
          eType="#//core/CobolStatementaxaxax" eOpposite="#//core/CobolStatementaxaxax/mapsTo"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CobolReferenceableElementaxax" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsTo" upperBound="-1"
          eType="#//core/KernelReferenceableElement" eOpposite="#//core/KernelReferenceableElement/mapsFrom"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KernelReferenceableElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsFrom" upperBound="-1"
          eType="#//core/CobolReferenceableElementaxax" eOpposite="#//core/CobolReferenceableElementaxax/mapsTo"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Kernel2CobolMapping" eSuperTypes="#//core/MappingRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="kernelCU" lowerBound="1"
          eType="#//core/KernelCompilationUnit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cobolCUs" upperBound="-1"
          eType="#//core/CobolCompilationUnitxsxsx" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
